tasks:
  - init: bash install.sh

github:
  prebuilds:
    # enable for the default branch (defaults to true)
    main: true
    # enable for all branches in this repo (defaults to false)
    branches: true
    # enable for pull requests coming from this repo (defaults to true)
    pullRequests: true
    # enable for pull requests coming from forks (defaults to false)
    pullRequestsFromForks: true
    # add a check to pull requests (defaults to true)
    addCheck: true
    # add a "Review in Gitpod" button as a comment to pull requests (defaults to false)
    addComment: true
    # add a "Review in Gitpod" button to the pull request's description (defaults to false)
    addBadge: false

vscode:
  extensions:
    - ms-vscode.live-server
    - DavidAnson.vscode-markdownlint
    - ms-azuretools.vscode-docker
    - codespaces-Contrib.codeswing
    - dbaeumer.vscode-eslint
    - eamodio.gitlens
    - esbenp.prettier-vscode
    - github.github-vscode-theme
    - mongodb.mongodb-vscode
    - ms-python.python
    - ms-toolsai.jupyter
    - ms-toolsai.jupyter-keymap
    - ms-toolsai.jupyter-renderers
    - pkief.material-icon-theme
    - redhat.java
    - streetsidesoftware.code-spell-checker
    - rust-lang.rust
    - octref.vetur
    - wayou.vscode-todo-highlight
    - vscjava.vscode-java-pack
    - https://vsext.netlify.app/ext/qwtel.sqlite-viewer.vsix
    - https://vsext.netlify.app/ext/github.copilot.vsix
    - https://vsext.netlify.app/ext/ms-python.vscode-pylance.vsix
    - https://vsext.netlify.app/ext/sdras.vue-vscode-snippets.vsix
    - https://vsext.netlify.app/ext/visualstudioexptteam.vscodeintellicode.vsix
