image:
  file: gitpod.Dockerfile
  
tasks:
  - before: bash install.sh

vscode:
  extensions:
    - ms-vscode.live-server
    - DavidAnson.vscode-markdownlint
    - rangav.vscode-thunder-client
    - ms-azuretools.vscode-docker
    - codespaces-Contrib.codeswing
    - dbaeumer.vscode-eslint
    - eamodio.gitlens
    - esbenp.prettier-vscode
    - github.github-vscode-theme
    - mongodb.mongodb-vscode
    - ms-python.python
    - ms-toolsai.jupyter
    - ms-toolsai.jupyter-keymap
    - ms-toolsai.jupyter-renderers
    - pkief.material-icon-theme
    - redhat.java
    - streetsidesoftware.code-spell-checker
    - octref.vetur
    - wayou.vscode-todo-highlight
    - vscjava.vscode-java-pack
    - https://vsext.netlify.app/ext/qwtel.sqlite-viewer.vsix
    - https://vsext.netlify.app/ext/rust-lang.rust-analyzer.vsix
    - https://vsext.netlify.app/ext/ms-python.vscode-pylance.vsix
    - https://vsext.netlify.app/ext/sdras.vue-vscode-snippets.vsix
    - https://vsext.netlify.app/ext/visualstudioexptteam.vscodeintellicode.vsix
    # - https://vsext.netlify.app/ext/github.copilot.vsix

