tasks:
  - before: bash install.sh
  - init: bash install.sh

github:
  prebuilds:
    # enable for the default branch (defaults to true)
    main: true
    # enable for all branches in this repo (defaults to false)
    branches: true
    # enable for pull requests coming from this repo (defaults to true)
    pullRequests: true
    # enable for pull requests coming from forks (defaults to false)
    pullRequestsFromForks: true
    # add a check to pull requests (defaults to true)
    addCheck: true
    # add a "Review in Gitpod" button as a comment to pull requests (defaults to false)
    addComment: true
    # add a "Review in Gitpod" button to the pull request's description (defaults to false)
    addBadge: false

vscode:
  extensions:
    - github.github-vscode-theme
    - ms-python.python
    - esbenp.prettier-vscode
    - pkief.material-icon-theme
    - eamodio.gitlens
    - mongodb.mongodb-vscode
    - yzhang.markdown-all-in-one